import { ACADEMIC_CATEGORIES } from "./academicCategories";

export const CREDIT_RULES = {
  [ACADEMIC_CATEGORIES.PROGRAM_CORE]: 4,

  [ACADEMIC_CATEGORIES.INDUSTRIAL_INTERNSHIP]: 4,

  [ACADEMIC_CATEGORIES.PRODUCT_DESIGN]: 8,

  [ACADEMIC_CATEGORIES.RESEARCH_PROJECT]: 12,

  [ACADEMIC_CATEGORIES.PROFESSIONAL_CERTIFICATION]: 4,

  [ACADEMIC_CATEGORIES.PROGRAM_ELECTIVE]: 4,
};